### ISSUE TITLE
HN

### ISSUE THREAD

**Issue by vanous** [msgre/minecraft#1]
Ahoy,

to se mi líbí, jak se posunují články na hacker news a lidé hvězdičkují stejná repa :))) 
Jo, jinak, nemáme spigot (minecraft) server na DO, ale provozujeme doma, pokud by jsi chtěl, tady je náš setup: https://github.com/vanous/random_scripts/tree/master/spigot ,  kdybyste se chtěli někdy připojit, dej vědět, pošlu adresu (viz ngrok ve scriptech) a přidám na whitelist, ale poslední dobou tam moc nebývám, spíše synátor.. ahoy!
P.

![mapa](https://matrix.org/_matrix/media/v1/thumbnail/matrix.org/zLAaiQKwLeWDvCnIwcmbzcDm?width=800&height=600)
[fill size](https://matrix.org/_matrix/media/v1/download/matrix.org/zLAaiQKwLeWDvCnIwcmbzcDm)

**Comment by msgre** [comment]
Čau! Jaké repa se na HN hvězdičkují? :)

**Comment by vanous** [comment]
Ahoj,

hvězdičkují repozitáře na githubu :)

https://github.com/stars/msgre
https://github.com/stars/vanous
https://github.com/stars/lusk
